version: "3"
services:

  gateway:
    image: nginx:alpine
    restart: always
    ports:
      - ${API_PUBLIC_PORT}:80
    volumes:
      - ${NGINX_CONF}:/etc/nginx/conf.d/default.conf:rw
      - ${CERTS_DIR}:/etc/nginx/certs:z
  redis:
    image: redis:alpine
    restart: always
    ports:
      - 6379
  mongo:
    # image: mvertes/alpine-mongo # MONGO ALPINE CONTAINER VERSION
    image: mongo:latest
    restart: always
    ports:
      - 27017
  auth-service:
    build:
      context: https://github.com/jhuygens/auth-service.git#master
    restart: always
    volumes:
      - ${API_CONFIG}:/app/config.json:rw
    ports:
      - 9091
  search-service:
    build:
      context: https://github.com/jhuygens/search-service.git#master
    restart: always
    volumes:
      - ${API_CONFIG}:/app/config.json:rw
    ports:
      - 9092

  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - ${MONGODB_EXPRESS_PUBLIC_PORT}:8081